FROM alpine

RUN apt-get update -y

RUN apt-get install py-pip python3-dev libffi-dev openssl-dev gcc libc-dev rust cargo make -y

RUN sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN sudo chmod +x /usr/local/bin/docker-compose


